"""fix price field name and add description field

Revision ID: feb3f690a428
Revises: df822737d8e8
Create Date: 2023-08-15 21:54:29.379587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb3f690a428'
down_revision: Union[str, None] = 'df822737d8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=True))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('product', 'print')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('print', sa.INTEGER(), nullable=True))
    op.drop_column('product', 'price')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
